### ISSUE TITLE
version: master fails with unhandled promise rejection

### ISSUE THREAD

**Issue by Vexu** [goto-bus-stop/setup-zig#4]
```
bin/tar x -C /home/runner/work/_temp/d6b098d2-58ec-433e-89ab-e3e9dfcc38e6 -f /home/runner/work/_temp/e7f54a5e-4597-4306-905a-cd556da6d3b6
(node:2710) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/home/runner/work/_temp/d6b098d2-58ec-433e-89ab-e3e9dfcc38e6/zig-linux-x86_64-master'
    at Object.statSync (fs.js:915:3)
    at Object.<anonymous> (/home/runner/work/_actions/goto-bus-stop/setup-zig/v1.2.0/dist/index.js:3612:17)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/goto-bus-stop/setup-zig/v1.2.0/dist/index.js:3352:71
    at new Promise (<anonymous>)
    at module.exports.533.__awaiter (/home/runner/work/_actions/goto-bus-stop/setup-zig/v1.2.0/dist/index.js:3348:12)
    at Object.cacheDir (/home/runner/work/_actions/goto-bus-stop/setup-zig/v1.2.0/dist/index.js:3607:12)
    at downloadZig (/home/runner/work/_actions/goto-bus-stop/setup-zig/v1.2.0/dist/index.js:1150:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2710) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
```yml
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
      - uses: goto-bus-stop/setup-zig@v1.2.0
        with:
          version: master
      - run: zig build test
```
