### ISSUE TITLE
Invalid version "master"

### ISSUE THREAD

**Issue by brodeuralexis** [goto-bus-stop/setup-zig#6]
Using the following configuration option:
```yml
name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
      - uses: goto-bus-stop/setup-zig@v1.0.0
        with:
          version: master
      - run: zig build test
```
Fails with the following error:
```
(node:2617) UnhandledPromiseRejectionWarning: TypeError: Invalid Version: master
    at new SemVer (/home/runner/work/_actions/goto-bus-stop/setup-zig/v1.0.0/node_modules/semver/semver.js:332:11)
    at compare (/home/runner/work/_actions/goto-bus-stop/setup-zig/v1.0.0/node_modules/semver/semver.js:647:10)
    at Function.lt (/home/runner/work/_actions/goto-bus-stop/setup-zig/v1.0.0/node_modules/semver/semver.js:688:10)
    at main (/home/runner/work/_actions/goto-bus-stop/setup-zig/v1.0.0/index.js:33:14)
    at Object.<anonymous> (/home/runner/work/_actions/goto-bus-stop/setup-zig/v1.0.0/index.js:44:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
(node:2617) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2617) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Link to failing CI commit: https://github.com/brodeuralexis/zasm-emulator/runs/433136634?check_suite_focus=true
